/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#002442",
        "primary-container": "#063a63",
        "on-primary": "#ffffff",
        "on-primary-container": "#7da5d4",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#a2cafb",
        "on-primary-fixed": "#001d36",
        "on-primary-fixed-variant": "#1d4973",
        
        "secondary": "#006971",
        "secondary-action": "#12b8c6",
        "secondary-container": "#69effe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006b74",
        "secondary-fixed": "#88f3ff",
        "secondary-fixed-dim": "#4dd8e7",
        "on-secondary-fixed": "#001f23",
        "on-secondary-fixed-variant": "#004f56",
        
        "tertiary": "#4f000e",
        "tertiary-container": "#77001b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff777f",
        "tertiary-fixed": "#ffdad9",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-tertiary-fixed": "#40000a",
        "on-tertiary-fixed-variant": "#920023",
        
        "error": "#dc3f50",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        "surface": "#f4faff",
        "surface-dim": "#ccdce7",
        "surface-bright": "#f4faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e8f6ff",
        "surface-container": "#dff0fc",
        "surface-container-high": "#daebf6",
        "surface-container-highest": "#d4e5f0",
        "surface-tint": "#38618c",
        
        "on-surface": "#0d1d25",
        "on-surface-variant": "#42474e",
        "inverse-surface": "#23323b",
        "inverse-on-surface": "#e2f3fe",
        
        "outline": "#73777f",
        "outline-variant": "#c2c7cf",
        "civic-border": "#d0e1ec",
        "background": "#f4faff",
        "on-background": "#0d1d25"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "1.5rem",
        "margin-mobile": "1rem",
        "gutter": "1rem",
        "gutter-mobile": "0.75rem"
      },
      fontFamily: {
        sans: ["'Public Sans'", "sans-serif"],
        "display-token": ["'Public Sans'", "sans-serif"],
        "headline-lg": ["'Public Sans'", "sans-serif"],
        "headline-md": ["'Public Sans'", "sans-serif"],
        "headline-sm": ["'Public Sans'", "sans-serif"],
        "body-lg": ["'Public Sans'", "sans-serif"],
        "body-md": ["'Public Sans'", "sans-serif"],
        "label-lg": ["'Public Sans'", "sans-serif"],
        "label-md": ["'Public Sans'", "sans-serif"],
        "bilingual-sub": ["'Public Sans'", "sans-serif"],
      },
      fontSize: {
        "display-token": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-token-mobile": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "700" }],
        "bilingual-sub": ["14px", { lineHeight: "18px", fontWeight: "500" }],
      }
    },
  },
  plugins: [],
}
